<?php
/**
 * Remove theme-generated boilerplate stored inside post content (CLI only).
 *
 *   php tools/clean-boilerplate.php [--apply] [--prepend=file.php]
 *
 * Only blocks that are certainly generated by the old theme are touched:
 *   - <!-- HPW-AUTO-CONTENT:START --> ... <!-- HPW-AUTO-CONTENT:END --> (the "thin content expansion" output)
 *   - <section class="hpw-auto-..."> ... </section> blocks (Update Notes, Overview, Checks, Fit, Signals, Alternatives, Risks)
 * Author-written paragraphs are never matched. Dry run unless --apply; the original content is kept in the
 * _hpw_pre_clean meta of each changed post.
 */
if ( 'cli' !== php_sapi_name() ) {
    exit( 'CLI only' );
}
$opts = getopt( '', array( 'apply', 'prepend::' ) );
if ( ! empty( $opts['prepend'] ) ) {
    require $opts['prepend'];
}
require dirname( __DIR__, 4 ) . '/wp-load.php';
$apply = isset( $opts['apply'] );
global $wpdb;

$patterns = array(
    '#<!-- HPW-AUTO-CONTENT:START -->.*?<!-- HPW-AUTO-CONTENT:END -->#s',
    '#<section class="hpw-auto-[a-z-]+">.*?</section>#s',
);
$rows    = $wpdb->get_results( "SELECT ID, post_title, post_content FROM {$wpdb->posts} WHERE post_type='post' AND post_status='publish' AND ( post_content LIKE '%HPW-AUTO-CONTENT%' OR post_content LIKE '%hpw-auto-%' )" );
$changed = 0;
$blocks  = 0;
foreach ( $rows as $r ) {
    $new = $r->post_content;
    foreach ( $patterns as $pat ) {
        $new = preg_replace( $pat, '', $new, -1, $n );
        $blocks += (int) $n;
    }
    $new = trim( preg_replace( "/\n{3,}/", "\n\n", $new ) );
    if ( $new === $r->post_content ) { continue; }
    $changed++;
    echo ( $apply ? 'CLEAN ' : 'DRY   ' ) . $r->ID . ' ' . $r->post_title . ' (' . strlen( $r->post_content ) . ' -> ' . strlen( $new ) . " chars)\n";
    if ( $apply ) {
        update_post_meta( $r->ID, '_hpw_pre_clean', $r->post_content );
        $wpdb->update( $wpdb->posts, array( 'post_content' => $new ), array( 'ID' => $r->ID ) );
        clean_post_cache( $r->ID );
    }
}
echo "Published posts with boilerplate: " . count( $rows ) . ", changed: $changed, blocks removed: $blocks" . ( $apply ? '' : ' (dry run)' ) . "\n";
